INSERT INTO breed (name) VALUES ('French Bulldogs');
INSERT INTO breed (name) VALUES ('Labrador Retrievers');
INSERT INTO breed (name) VALUES ('Golden Retrievers');
INSERT INTO breed (name) VALUES ('German Shepherd Dogs');
INSERT INTO breed (name) VALUES ('Poodles');
INSERT INTO breed (name) VALUES ('Bulldogs');
INSERT INTO breed (name) VALUES ('Rottweilers');
INSERT INTO breed (name) VALUES ('Beagles');
INSERT INTO breed (name) VALUES ('Dachshunds');
INSERT INTO breed (name) VALUES ('German Shorthaired Pointers');